//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class equipment {
    
    private string slotField;
    
    private string idField;
    
    private string amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slot {
        get {
            return this.slotField;
        }
        set {
            this.slotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NPCCharacters {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NPCCharacter", typeof(NPCCharactersNPCCharacter), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("equipment", typeof(equipment))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacter {
    
    private NPCCharactersNPCCharacterFace[] faceField;
    
    private NPCCharactersNPCCharacterHero[] heroField;
    
    private NPCCharactersNPCCharacterComponents[] componentsField;
    
    private NPCCharactersNPCCharacterSkillsSkill[] skillsField;
    
    private NPCCharactersNPCCharacterTraitsTrait[] traitsField;
    
    private NPCCharactersNPCCharacterFeatsFeat[] featsField;
    
    private NPCCharactersNPCCharacterEquipmentSet[] equipmentSetField;
    
    private equipment[] equipmentField;
    
    private NPCCharactersNPCCharacterUpgrade_targetsUpgrade_target[] upgrade_targetsField;
    
    private string idField;
    
    private string default_groupField;
    
    private string voiceField;
    
    private string is_heroField;
    
    private string is_femaleField;
    
    private string is_basic_troopField;
    
    private bool is_templateField;
    
    private bool is_templateFieldSpecified;
    
    private bool is_child_templateField;
    
    private bool is_child_templateFieldSpecified;
    
    private string cultureField;
    
    private string nameField;
    
    private string banner_symbol_mesh_nameField;
    
    private string banner_symbol_colorField;
    
    private string banner_keyField;
    
    private string occupationField;
    
    private string civilianTemplateField;
    
    private string battleTemplateField;
    
    private string is_companionField;
    
    private string offsetField;
    
    private string levelField;
    
    private string ageField;
    
    private string is_mercenaryField;
    
    private string formation_position_preferenceField;
    
    private string default_equipment_setField;
    
    private string skill_templateField;
    
    private string upgrade_requiresField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("face", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterFace[] face {
        get {
            return this.faceField;
        }
        set {
            this.faceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hero", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterHero[] Hero {
        get {
            return this.heroField;
        }
        set {
            this.heroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Components", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterComponents[] Components {
        get {
            return this.componentsField;
        }
        set {
            this.componentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("skill", typeof(NPCCharactersNPCCharacterSkillsSkill), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NPCCharactersNPCCharacterSkillsSkill[] skills {
        get {
            return this.skillsField;
        }
        set {
            this.skillsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Trait", typeof(NPCCharactersNPCCharacterTraitsTrait), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NPCCharactersNPCCharacterTraitsTrait[] Traits {
        get {
            return this.traitsField;
        }
        set {
            this.traitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("feat", typeof(NPCCharactersNPCCharacterFeatsFeat), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NPCCharactersNPCCharacterFeatsFeat[] feats {
        get {
            return this.featsField;
        }
        set {
            this.featsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("equipmentSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterEquipmentSet[] equipmentSet {
        get {
            return this.equipmentSetField;
        }
        set {
            this.equipmentSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("equipment")]
    public equipment[] equipment {
        get {
            return this.equipmentField;
        }
        set {
            this.equipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("upgrade_target", typeof(NPCCharactersNPCCharacterUpgrade_targetsUpgrade_target), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NPCCharactersNPCCharacterUpgrade_targetsUpgrade_target[] upgrade_targets {
        get {
            return this.upgrade_targetsField;
        }
        set {
            this.upgrade_targetsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string default_group {
        get {
            return this.default_groupField;
        }
        set {
            this.default_groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string voice {
        get {
            return this.voiceField;
        }
        set {
            this.voiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_hero {
        get {
            return this.is_heroField;
        }
        set {
            this.is_heroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_female {
        get {
            return this.is_femaleField;
        }
        set {
            this.is_femaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_basic_troop {
        get {
            return this.is_basic_troopField;
        }
        set {
            this.is_basic_troopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool is_template {
        get {
            return this.is_templateField;
        }
        set {
            this.is_templateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool is_templateSpecified {
        get {
            return this.is_templateFieldSpecified;
        }
        set {
            this.is_templateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool is_child_template {
        get {
            return this.is_child_templateField;
        }
        set {
            this.is_child_templateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool is_child_templateSpecified {
        get {
            return this.is_child_templateFieldSpecified;
        }
        set {
            this.is_child_templateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string culture {
        get {
            return this.cultureField;
        }
        set {
            this.cultureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string banner_symbol_mesh_name {
        get {
            return this.banner_symbol_mesh_nameField;
        }
        set {
            this.banner_symbol_mesh_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string banner_symbol_color {
        get {
            return this.banner_symbol_colorField;
        }
        set {
            this.banner_symbol_colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string banner_key {
        get {
            return this.banner_keyField;
        }
        set {
            this.banner_keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string occupation {
        get {
            return this.occupationField;
        }
        set {
            this.occupationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string civilianTemplate {
        get {
            return this.civilianTemplateField;
        }
        set {
            this.civilianTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string battleTemplate {
        get {
            return this.battleTemplateField;
        }
        set {
            this.battleTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_companion {
        get {
            return this.is_companionField;
        }
        set {
            this.is_companionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_mercenary {
        get {
            return this.is_mercenaryField;
        }
        set {
            this.is_mercenaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formation_position_preference {
        get {
            return this.formation_position_preferenceField;
        }
        set {
            this.formation_position_preferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string default_equipment_set {
        get {
            return this.default_equipment_setField;
        }
        set {
            this.default_equipment_setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string skill_template {
        get {
            return this.skill_templateField;
        }
        set {
            this.skill_templateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string upgrade_requires {
        get {
            return this.upgrade_requiresField;
        }
        set {
            this.upgrade_requiresField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFace {
    
    private NPCCharactersNPCCharacterFaceFace_key[] face_keyField;
    
    private NPCCharactersNPCCharacterFaceBodyProperties[] bodyPropertiesField;
    
    private NPCCharactersNPCCharacterFaceBodyPropertiesMax[] bodyPropertiesMaxField;
    
    private NPCCharactersNPCCharacterFaceFace_key_template[] face_key_templateField;
    
    private NPCCharactersNPCCharacterFaceHair_tagsHair_tag[] hair_tagsField;
    
    private NPCCharactersNPCCharacterFaceBeard_tagsBeard_tag[] beard_tagsField;
    
    private NPCCharactersNPCCharacterFaceTattoo_tagsTattoo_tag[] tattoo_tagsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("face_key", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterFaceFace_key[] face_key {
        get {
            return this.face_keyField;
        }
        set {
            this.face_keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BodyProperties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterFaceBodyProperties[] BodyProperties {
        get {
            return this.bodyPropertiesField;
        }
        set {
            this.bodyPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BodyPropertiesMax", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterFaceBodyPropertiesMax[] BodyPropertiesMax {
        get {
            return this.bodyPropertiesMaxField;
        }
        set {
            this.bodyPropertiesMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("face_key_template", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterFaceFace_key_template[] face_key_template {
        get {
            return this.face_key_templateField;
        }
        set {
            this.face_key_templateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("hair_tag", typeof(NPCCharactersNPCCharacterFaceHair_tagsHair_tag), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NPCCharactersNPCCharacterFaceHair_tagsHair_tag[] hair_tags {
        get {
            return this.hair_tagsField;
        }
        set {
            this.hair_tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("beard_tag", typeof(NPCCharactersNPCCharacterFaceBeard_tagsBeard_tag), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NPCCharactersNPCCharacterFaceBeard_tagsBeard_tag[] beard_tags {
        get {
            return this.beard_tagsField;
        }
        set {
            this.beard_tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("tattoo_tag", typeof(NPCCharactersNPCCharacterFaceTattoo_tagsTattoo_tag), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NPCCharactersNPCCharacterFaceTattoo_tagsTattoo_tag[] tattoo_tags {
        get {
            return this.tattoo_tagsField;
        }
        set {
            this.tattoo_tagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFaceFace_key {
    
    private string valueField;
    
    private string max_valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string max_value {
        get {
            return this.max_valueField;
        }
        set {
            this.max_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFaceBodyProperties {
    
    private string versionField;
    
    private string ageField;
    
    private string weightField;
    
    private string buildField;
    
    private string keyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string build {
        get {
            return this.buildField;
        }
        set {
            this.buildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFaceBodyPropertiesMax {
    
    private string versionField;
    
    private string ageField;
    
    private string weightField;
    
    private string buildField;
    
    private string keyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string build {
        get {
            return this.buildField;
        }
        set {
            this.buildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFaceFace_key_template {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFaceHair_tagsHair_tag {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFaceBeard_tagsBeard_tag {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFaceTattoo_tagsTattoo_tag {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterHero {
    
    private string banner_keyField;
    
    private string is_nobleField;
    
    private string idField;
    
    private string textField;
    
    private string spouseField;
    
    private string aliveField;
    
    private string voiceField;
    
    private string fatherField;
    
    private string motherField;
    
    private string factionField;
    
    private string clanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string banner_key {
        get {
            return this.banner_keyField;
        }
        set {
            this.banner_keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string is_noble {
        get {
            return this.is_nobleField;
        }
        set {
            this.is_nobleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string spouse {
        get {
            return this.spouseField;
        }
        set {
            this.spouseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alive {
        get {
            return this.aliveField;
        }
        set {
            this.aliveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string voice {
        get {
            return this.voiceField;
        }
        set {
            this.voiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string father {
        get {
            return this.fatherField;
        }
        set {
            this.fatherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mother {
        get {
            return this.motherField;
        }
        set {
            this.motherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string faction {
        get {
            return this.factionField;
        }
        set {
            this.factionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clan {
        get {
            return this.clanField;
        }
        set {
            this.clanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterComponents {
    
    private NPCCharactersNPCCharacterComponentsCompanion[] companionField;
    
    private NPCCharactersNPCCharacterComponentsLord[] lordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Companion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterComponentsCompanion[] Companion {
        get {
            return this.companionField;
        }
        set {
            this.companionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NPCCharactersNPCCharacterComponentsLord[] Lord {
        get {
            return this.lordField;
        }
        set {
            this.lordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterComponentsCompanion {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterComponentsLord {
    
    private string idField;
    
    private string banner_keyField;
    
    private string spouseField;
    
    private string voiceField;
    
    private string fatherField;
    
    private string motherField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string banner_key {
        get {
            return this.banner_keyField;
        }
        set {
            this.banner_keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string spouse {
        get {
            return this.spouseField;
        }
        set {
            this.spouseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string voice {
        get {
            return this.voiceField;
        }
        set {
            this.voiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string father {
        get {
            return this.fatherField;
        }
        set {
            this.fatherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mother {
        get {
            return this.motherField;
        }
        set {
            this.motherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterSkillsSkill {
    
    private string idField;
    
    private int valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterTraitsTrait {
    
    private string idField;
    
    private int valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterFeatsFeat {
    
    private string idField;
    
    private int valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterEquipmentSet {
    
    private equipment[] equipmentField;
    
    private string civilianField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("equipment")]
    public equipment[] equipment {
        get {
            return this.equipmentField;
        }
        set {
            this.equipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string civilian {
        get {
            return this.civilianField;
        }
        set {
            this.civilianField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NPCCharactersNPCCharacterUpgrade_targetsUpgrade_target {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
